# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: org.apache.dubbo.spring.boot.demo.provider.service

  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  ## dubbo.application.name=${spring.application.name}

  # Dubbo Protocol
  protocol:
    name: dubbo
    port: 8002

  ## Dubbo Registry
  registry:
    address: nacos://127.0.0.1:8848